spring:
  profiles:
    active: default
  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-file-size: 128KB
      max-request-size: 128KB
  application:
    name: instana

  springdoc:
    version: '@springdoc.version@'
    api-docs:
      version: openapi_3_1
    swagger-ui:
      use-root-path: true