spring:
  profiles:
    active: default
  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-file-size: 128KB
      max-request-size: 128KB
  application:
    name: instana

  springdoc:
    version: '@springdoc.version@'
    api-docs:
      version: openapi_3_1
    swagger-ui:
      use-root-path: true

  single-line-input: Input/single-line-input.txt
  multi-line-input: Input/multi-line-input.txt
  empty-input: Input/empty-input.txt
  mixed-input: Input/mixed-input.txt
  sample-input: Input/sample-input.txt
  malformed-input: Input/malformed-input.txt

  single-line-output: Output/single-line-output.txt
  multi-line-output: Output/multi-line-output.txt